default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: lemon
  host: mysql
  #socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: thorn_development

test:
  <<: *default
  database: thorn_test

production:
  <<: *default
  database: thorn_production
  username: root
  password: lemon

docker:
  <<: *default
  database: thorn
  username: root
  password: lemon
