default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  #host: mysql
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: torn_development

test:
  <<: *default
  database: torn_test

production:
  <<: *default
  database: torn_production
  username: root
  password: root
