version: '2.1'
services:

  ### Lemonade DB ##
  lemonade_db:
    image: mysql
    command: mysqld --character-set-server=utf8
      --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
      --innodb-flush-log-at-trx-commit=0 --bind-address=0.0.0.0
    environment:
      - MYSQL_ROOT_PASSWORD=lemon
<<<<<<< HEAD
    ports:
      - 33061:3306
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - /srv/lemonade/mysql-stage:/var/lib/mysql
=======
    volumes:
      - ./extras/initdb.d:/docker-entrypoint-initdb.d
      - /srv/lemonade/mysql:/var/lib/mysql
>>>>>>> f8de7e5... Change submodules repo to HTTPS and move conf files
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "root", "-plemon", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  ### Redis ###
  redis:
    image: redis

  ### Limonero ###
  limonero:
    image: eubrabigsea/limonero
    links:
      - lemonade_db:mysql
      - thorn:thorn
    environment: 
      - HADOOP_CONF_DIR=/usr/local/juicer/conf
    volumes:
      - ./config/limonero-config.yaml:/usr/local/limonero/conf/limonero-config.yaml
      - ./config/logging_config.ini:/usr/local/limonero/logging_config.ini
      - /srv/lemonade/logs:/usr/local/limonero/logs/
    depends_on:
      lemonade_db:
        condition: service_healthy

  ### Juicer ###
  juicer:
    image: eubrabigsea/juicer
    environment:
      - HADOOP_CONF_DIR=/usr/local/juicer/conf
    links:
      - stand
      - limonero
      - tahiti
      - thorn
    volumes:
      - ./config/juicer-config.yaml:/usr/local/juicer/conf/juicer-config.yaml
      - ./config/logging_config.ini:/usr/local/juicer/logging_config.ini
      - ./config/hdfs-site.xml:/usr/local/juicer/conf/hdfs-site.xml
      - /srv/lemonade/logs:/usr/local/juicer/logs/

  ### Stand ###
  stand:
    image: eubrabigsea/stand
    links:
      - lemonade_db:mysql
      - thorn:thorn
    volumes:
      - ./config/stand-config.yaml:/usr/local/stand/conf/stand-config.yaml
      - ./config/logging_config.ini:/usr/local/stand/logging_config.ini
      - /srv/lemonade/logs:/usr/local/stand/logs/
    depends_on:
      lemonade_db:
        condition: service_healthy

  ### Caipirinha ###
  caipirinha:
    image: eubrabigsea/caipirinha
    links:
      - lemonade_db:mysql
      - thorn:thorn
    volumes:
      - ./config/caipirinha-config.yaml:/usr/local/caipirinha/conf/caipirinha-config.yaml
      - ./config/logging_config.ini:/usr/local/caipirinha/logging_config.ini
      - /srv/lemonade/logs:/usr/local/caipirinha/logs/
    depends_on:
      lemonade_db:
        condition: service_healthy

  ### Tahiti ###
  tahiti:
    image: eubrabigsea/tahiti
    links:
      - lemonade_db:mysql
      - thorn:thorn
    volumes:
      - ./config/tahiti-config.yaml:/usr/local/tahiti/conf/tahiti-config.yaml
      - ./config/logging_config.ini:/usr/local/tahiti/logging_config.ini
      - /srv/lemonade/logs:/usr/local/tahiti/logs/
    depends_on:
      lemonade_db:
        condition: service_healthy

  ### Thorn ###
  thorn:
<<<<<<< HEAD
     image: eubrabigsea/thorn
     environment:
        - RAILS_CORS_ORIGINS=*
        - LEMONADE_ENV=teste.ctweb.inweb.org.br
        - EMAIL_PROVIDER_USERNAME=lemonade.suporte
        - EMAIL_PROVIDER_PASSWORD=zooropa2017
     volumes:
        - ./database.yml:/usr/src/app/config/database.yml
     ports:
        - '3000:3000'
     links:
        - lemonade_db:mysql
     depends_on:
        lemonade_db:
            condition: service_healthy
=======
    image: eubrabigsea/thorn
    environment:
      - RAILS_CORS_ORIGINS=*
      - LEMONADE_ENV=dev.ctweb.inweb.org.br
      - EMAIL_PROVIDER_USERNAME=lemonade.suporte
      - EMAIL_PROVIDER_PASSWORD=zooropa2017
    volumes:
      - ./config/database.yml:/usr/src/app/config/database.yml
    links:
      - lemonade_db:mysql
    depends_on:
      lemonade_db:
        condition: service_healthy
>>>>>>> f8de7e5... Change submodules repo to HTTPS and move conf files

  ### Citron ###
  citron:
    image: eubrabigsea/citron
    ports:
      - '23450:8080'
    volumes:
      - ./config/env.json:/usr/local/citron/dist/env.json
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - thorn
      - limonero
      - tahiti
      - stand
