version: '3'
services:

  ### Lemonade DB ##
  mysql:
    image: mysql
    command: mysqld --character-set-server=utf8
      --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
      --innodb-flush-log-at-trx-commit=0 --bind-address=0.0.0.0
    environment:
      - MYSQL_ROOT_PASSWORD=lemon
    volumes:
      - /srv/docker-lemonade/extras/initdb.d:/docker-entrypoint-initdb.d
      - /srv/lemonade/mysql:/var/lib/mysql
    networks:
      default:
        aliases: [db, lemonade_db]
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "root", "-plemon", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
#      placement:
#        constraints: [node.volume == 'mapped']
      restart_policy:
        condition: on-failure

  ### Limonero ###
  limonero:
    image: eubrabigsea/limonero
    environment:
      - HADOOP_CONF_DIR=/usr/local/juicer/conf
    volumes:
      - /srv/docker-lemonade/config/limonero-config.yaml:/usr/local/limonero/conf/limonero-config.yaml
      - /srv/docker-lemonade/config/logging_config.ini:/usr/local/limonero/logging_config.ini
      - /srv/lemonade/logs:/usr/local/limonero/logs/
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=PathPrefixStrip:/limonero
      - traefik.port=23402
    networks:
      - default
    depends_on:
      - db
      - thorn
    deploy:
      restart_policy:
        condition: any

  ### Juicer ###
  juicer:
    image: eubrabigsea/juicer
    environment:
      - HADOOP_CONF_DIR=/usr/local/juicer/conf
    volumes:
       - /srv/docker-lemonade/config/juicer-config.yaml:/usr/local/juicer/conf/juicer-config.yaml
       - /srv/docker-lemonade/config/logging_config.ini:/usr/local/juicer/logging_config.ini
       - /srv/docker-lemonade/config/hdfs-site.xml:/usr/local/juicer/conf/hdfs-site.xml
       - /srv/lemonade/logs:/usr/local/juicer/logs/
    networks:
      - default
    depends_on:
      - stand
      - limonero
      - tahiti
      - thorn
    deploy:
      restart_policy:
        condition: any

  ### Stand ###
  stand:
    image: eubrabigsea/stand
    volumes:
      - /srv/docker-lemonade/config/stand-config.yaml:/usr/local/stand/conf/stand-config.yaml
      - /srv/docker-lemonade/config/logging_config.ini:/usr/local/stand/logging_config.ini
      - /srv/lemonade/logs:/usr/local/stand/logs/
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=PathPrefixStrip:/stand
      - traefik.port=23404
    networks:
      - default
    depends_on:
      - db
      - thorn
    deploy:
      restart_policy:
        condition: any

  ### Caipirinha ###
  caipirinha:
    image: eubrabigsea/caipirinha
    volumes:
      - /srv/docker-lemonade/config/caipirinha-config.yaml:/usr/local/caipirinha/conf/caipirinha-config.yaml
      - /srv/docker-lemonade/config/logging_config.ini:/usr/local/caipirinha/logging_config.ini
      - /srv/lemonade/logs:/usr/local/caipirinha/logs/
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=PathPrefixStrip:/caipirinha
      - traefik.port=23401
    networks:
      - default
    depends_on:
      - db
      - thorn
    deploy:
      restart_policy:
        condition: any

  ### Tahiti ###
  tahiti:
    image: eubrabigsea/tahiti
    volumes:
      - /srv/docker-lemonade/config/tahiti-config.yaml:/usr/local/tahiti/conf/tahiti-config.yaml
      - /srv/docker-lemonade/config/logging_config.ini:/usr/local/tahiti/logging_config.ini
      - /srv/lemonade/logs:/usr/local/tahiti/logs/
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=PathPrefixStrip:/tahiti
      - traefik.port=23403
    networks:
      - default
    depends_on:
      - db
      - thorn
    deploy:
      restart_policy:
        condition: any

  ### Thorn ###
  thorn:
    image: eubrabigsea/thorn
    environment:
      - RAILS_CORS_ORIGINS=*
    volumes:
      - /srv/docker-lemonade/config/database.yml:/usr/src/app/config/database.yml
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=PathPrefixStrip:/thorn
      - traefik.port=3000
    networks:
      - default
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: any


  ### Citron ###
  citron:
    image: eubrabigsea/citron
    volumes:
      - /srv/docker-lemonade/config/env.json:/usr/local/citron/dist/env.json
      - /srv/docker-lemonade/config/nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=PathPrefixStrip:/
      - traefik.port=8080
    depends_on:
      - thorn
      - limonero
      - tahiti
      - stand
    networks:
      - default
    deploy:
      restart_policy:
        condition: any

  ### Redis ###
  redis:
    image: redis

  ### traefik ###
  traefik:
    image: traefik:latest
    volumes:
      #- ./traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 8080:8080
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure

networks:
  default:
volumes:
  dbdata:
