version: '2.1'
services:
  ### Lemonade DB ##
  lemonade_db:
    image: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0 --bind-address=0.0.0.0
    environment:
      - MYSQL_ROOT_PASSWORD=lemon
    ports:
      - 33062:3306
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - /srv/lemonade/mysql:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "-u", "root", "-plemon", "status"]
        interval: 30s
        timeout: 10s
        retries: 5

  ### Limonero ###
  limonero:
    image: eubrabigsea/limonero
    links:
      - lemonade_db:mysql
      - thorn:thorn
    volumes:
      - ./limonero-config.yaml:/usr/local/limonero/conf/limonero-config.yaml
      - ./logging_config.ini:/usr/local/limonero/logging_config.ini
      - /srv/lemonade/logs:/usr/local/limonero/logs/
    depends_on:
        lemonade_db:
            condition: service_healthy

  ### Juicer ###
  juicer:
    image: eubrabigsea/juicer
    tty: true
    stdin_open: true
    environment: 
      - HADOOP_CONF_DIR=/usr/local/juicer/conf
    links:
      - stand
      - limonero
      - tahiti
      - thorn
    volumes:
       - ./juicer-config.yaml:/usr/local/juicer/conf/juicer-config.yaml
       - ./logging_config.ini:/usr/local/juicer/logging_config.ini
       - /srv/lemonade/logs:/usr/local/juicer/logs/
       - ./extras/hdfs-site.xml:/usr/local/juicer/conf/hdfs-site.xml

  ### Stand ###
  stand:
     image: eubrabigsea/stand
     tty: true
     stdin_open: true
     links:
      - lemonade_db:mysql
      - thorn:thorn
     volumes:
       - ./stand-config.yaml:/usr/local/stand/conf/stand-config.yaml
       - ./logging_config.ini:/usr/local/stand/logging_config.ini
       - /srv/lemonade/logs:/usr/local/stand/logs/
     depends_on:
        lemonade_db:
            condition: service_healthy

  ### Caipirinha ###
  caipirinha:
     image: eubrabigsea/caipirinha
     tty: true
     stdin_open: true
     links:
      - lemonade_db:mysql
      - thorn:thorn
     volumes:
       - ./caipirinha-config.yaml:/usr/local/caipirinha/conf/caipirinha-config.yaml
       - ./logging_config.ini:/usr/local/caipirinha/logging_config.ini
       - /srv/lemonade/logs:/usr/local/caipirinha/logs/
     depends_on:
        lemonade_db:
            condition: service_healthy

  ### Tahiti ###
  tahiti:
     image: eubrabigsea/tahiti
     tty: true
     stdin_open: true
     links:
      - lemonade_db:mysql
      - thorn:thorn
     volumes:
       - ./tahiti-config.yaml:/usr/local/tahiti/conf/tahiti-config.yaml
       - ./logging_config.ini:/usr/local/tahiti/logging_config.ini
       - /srv/lemonade/logs:/usr/local/tahiti/logs/
     ports:
        - '23403:23403'
     depends_on:
        lemonade_db:
            condition: service_healthy

  ### Thorn ###
  thorn:
     image: eubrabigsea/thorn
     environment:
        - RAILS_CORS_ORIGINS=*
        - LEMONADE_ENV=dev.ctweb.inweb.org.br
        - EMAIL_PROVIDER_USERNAME=lemonade.suporte
        - EMAIL_PROVIDER_PASSWORD=zooropa2017
     volumes:
        - ./database.yml:/usr/src/app/config/database.yml
     ports:
        - '3000:3000'
     links:
        - lemonade_db:mysql
     depends_on:
        lemonade_db:
            condition: service_healthy

  ### Citron ###
  citron:
     image: eubrabigsea/citron
     ports:
        - '23450:8080'
     volumes:
        - ./env.json:/usr/local/citron/dist/env.json
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
     links:
      - thorn
      - limonero
      - tahiti
      - stand

  ### Redis ###
  redis:
    image: "redis"
