version: '3'
services:

  ### Lemonade DB ##
  db:
    image: mysql
    command: mysqld --character-set-server=utf8
      --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
      --innodb-flush-log-at-trx-commit=0 --bind-address=0.0.0.0
    environment:
      - MYSQL_ROOT_PASSWORD=lemon
    volumes:
      - ./extras/initdb.d:/docker-entrypoint-initdb.d
      - /srv/lemonade/mysql:/var/lib/mysql
    networks:
      lemonade:
        aliases: [mysql, lemonade_db]
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "root", "-plemon", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      #      placement:
      #        constraints: [node.volume == 'mapped']
      restart_policy:
        condition: on-failure

  ### Limonero ###
  limonero:
    image: eubrabigsea/limonero
    environment:
      - HADOOP_CONF_DIR=/usr/local/juicer/conf
    volumes:
      - ./config/limonero-config.yaml:/usr/local/limonero/conf/limonero-config.yaml
      - ./config/logging_config.ini:/usr/local/limonero/logging_config.ini
      - /srv/lemonade/logs:/usr/local/limonero/logs/
    networks:
      - lemonade
    depends_on:
      - db
      - thorn
    deploy:
      restart_policy:
        condition: any

  ### Juicer ###
  juicer:
    image: eubrabigsea/juicer
    environment:
      - HADOOP_CONF_DIR=/usr/local/juicer/conf
    volumes:
       - ./config/juicer-config.yaml:/usr/local/juicer/conf/juicer-config.yaml
       - ./config/logging_config.ini:/usr/local/juicer/logging_config.ini
       - ./config/hdfs-site.xml:/usr/local/juicer/conf/hdfs-site.xml
       - /srv/lemonade/logs:/usr/local/juicer/logs/
    networks:
      - lemonade
    depends_on:
      - stand
      - limonero
      - tahiti
      - thorn
    deploy:
      restart_policy:
        condition: any

  ### Stand ###
  stand:
    image: eubrabigsea/stand
    volumes:
      - ./config/stand-config.yaml:/usr/local/stand/conf/stand-config.yaml
      - ./config/logging_config.ini:/usr/local/stand/logging_config.ini
      - /srv/lemonade/logs:/usr/local/stand/logs/
    networks:
      - lemonade
    depends_on:
      - db
      - thorn
    deploy:
      restart_policy:
        condition: any

  ### Caipirinha ###
  caipirinha:
    image: eubrabigsea/caipirinha
    volumes:
      - ./config/caipirinha-config.yaml:/usr/local/caipirinha/conf/caipirinha-config.yaml
      - ./config/logging_config.ini:/usr/local/caipirinha/logging_config.ini
      - /srv/lemonade/logs:/usr/local/caipirinha/logs/
    networks:
      - lemonade
    depends_on:
      - db
      - thorn
    deploy:
      restart_policy:
        condition: any

  ### Tahiti ###
  tahiti:
    image: eubrabigsea/tahiti
    volumes:
      - ./config/tahiti-config.yaml:/usr/local/tahiti/conf/tahiti-config.yaml
      - ./config/logging_config.ini:/usr/local/tahiti/logging_config.ini
      - /srv/lemonade/logs:/usr/local/tahiti/logs/
    depends_on:
      - db
      - thorn
    deploy:
      restart_policy:
        condition: any

  ### Thorn ###
  thorn:
     image: eubrabigsea/thorn
     environment:
        - RAILS_CORS_ORIGINS=*
     volumes:
        - ./config/database.yml:/usr/src/app/config/database.yml
    networks:
      - lemonade
     depends_on:
       - db
    deploy:
      restart_policy:
        condition: any


  ### Citron ###
  citron:
    image: eubrabigsea/citron
    ports:
      - '80:8080'
    volumes:
      - ./config/env.json:/usr/local/citron/dist/env.json
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lemonade
    depends_on:
      - thorn
      - limonero
      - tahiti
      - stand
    deploy:
      restart_policy:
        condition: any

  ### Redis ###
  redis:
    image: redis
    networks:
      - lemonade

networks:
  lemonade:
