# Tahiti configuration file
tahiti:
    debug: false
    environment: prod
    secret: Wl1ba1j57f 
    port: 23403
    servers:
        database_url: mysql+pymysql://root:lemon@mysql/tahiti
    services:
        thorn:
            url: http://thorn:23405
    config:
        SQLALCHEMY_POOL_SIZE: 0
        SQLALCHEMY_POOL_RECYCLE: 60

