# Juicer configuration file
juicer:
    debug: true
    servers:
        redis_url: redis://redis:6379
    services:
        tahiti:
            url: http://tahiti:23403
            auth_token: '123456'
        limonero:
            url: http://limonero:23402
            auth_token: '123456'
        stand:
            url: http://stand:23404
            auth_token: '123456'
        caipirinha:
            url: http://caipirinha:23401
            auth_token: '123456'
            storage_id: 2
    config:
        tmp_dir: /tmp
    spark:
        spark.executor.memory: 1g
        spark.executor.cores: 1
        spark.cores.max: 2
        spark.driver.memory: 2g
        # Allowed URLS:
        # local:                Run locally with 1 worker thread
        # local[k]:             Run locally with k worker threads
        # local[*]:             Run locally with as many worker threads as logical cores
        # spark://host:port:    Connect to Spark standalone cluster (default port 7077)
        # mesos://host:port:    Connect to Mesos cluster (default port 5050)
        # yarn:                 Connect to Yarn cluster. Cluster location will be found based
        #                       on the HADOOP_CONF_DIR or YARN_CONF_DIR variable.
        spark.master: local[*]
        spark.localdir: /tmp
        spark.driver.extraClassPath:
            "/usr/local/juicer/jars/lemonade-spark-ext-1.0-SNAPSHOT.jar"
